import type { ComplianceItem, Note, Property, Task, Unit } from './types'

/**
 * The buildings confirmed as managed by Rock Solid, seeded on first run so the
 * app opens with a real portfolio rather than an empty shell.
 *
 * This is a starting point, not a roster of record:
 *  - Only the units that surfaced in Tahari marketing material are here, which
 *    means the vacant ones. Use "Add many" on each building to put the real
 *    roster in.
 *  - 515 W 47th St and 323 E 108th St have no detail at all — nothing in the
 *    source files mentions them.
 *  - The filings carry the standard citywide dates. Anything on a per-building
 *    cycle (LL152, FISP, elevator, boiler, LL84/87/97) is a lookup task
 *    instead, because a guessed compliance date is worse than none.
 *
 * Delete this file and its import in store.ts to ship the app without it.
 */


export const PORTFOLIO_PROPERTIES: Property[] = [
  {
    id: "p_303w116",
    address: "303 W 116th St",
    submarket: "South Harlem",
    type: "mixed-use",
    unitCount: 3,
    superName: "",
    superPhone: "",
    hpdRegistration: "",
    blockLot: "",
    notes: "Confirmed as managed by you (31 Aug 2026).\n\nNew York, NY 10026. Columbia / Barnard / Morningside Heights, five-minute walk to campus. Virtual doorman. Ground-floor retail \u00b11,500 SF. Marketed no-broker-fee to students.\n\nLeasing contacts: Ricky Bustamante, Justin Stern.",
    archived: false,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "p_1875lex",
    address: "1875 Lexington Ave",
    submarket: "East Harlem",
    type: "multifamily",
    unitCount: 3,
    superName: "",
    superPhone: "",
    hpdRegistration: "",
    blockLot: "",
    notes: "Confirmed as managed by you (31 Aug 2026).\n\nResidential. Units below appeared in the Jul and Aug 2026 availability blasts \u2014 confirm which are still vacant.",
    archived: false,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "p_6aveb",
    address: "6 Avenue B",
    submarket: "East Village",
    type: "multifamily",
    unitCount: 2,
    superName: "",
    superPhone: "",
    hpdRegistration: "",
    blockLot: "",
    notes: "Confirmed as managed by you (31 Aug 2026).\n\nResidential. Not to be confused with 42, 44 or 60 Avenue B, which are separate Tahari listings. Units below are from the Jul and Aug 2026 blasts \u2014 confirm status.",
    archived: false,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "p_515w47",
    address: "515 W 47th St",
    submarket: "Hell's Kitchen",
    type: "multifamily",
    unitCount: 0,
    superName: "",
    superPhone: "",
    hpdRegistration: "",
    blockLot: "",
    notes: "Confirmed as managed by you (31 Aug 2026).\n\nNo detail in the Tahari files \u2014 everything here needs filling in from the office.",
    archived: false,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "p_323e108",
    address: "323 E 108th St",
    submarket: "East Harlem",
    type: "multifamily",
    unitCount: 0,
    superName: "",
    superPhone: "",
    hpdRegistration: "",
    blockLot: "",
    notes: "Confirmed as managed by you (31 Aug 2026).\n\nNo detail in the Tahari files \u2014 everything here needs filling in from the office. Not the same building as 301 E 108th St, which is a Tahari retail listing.",
    archived: false,
    createdAt: "2026-08-31T16:11:56.013433"
  }
]

export const PORTFOLIO_UNITS: Unit[] = [
  {
    id: "u_p_303w116_ph",
    propertyId: "p_303w116",
    label: "PH",
    tenantName: "",
    tenantPhone: "",
    tenantEmail: "",
    leaseStart: "",
    leaseEnd: "",
    rent: 0,
    stabilized: false,
    status: "vacant",
    notes: "4 bed / 2 bath. Open city views. Was available 1 Jul 2026 \u2014 confirm status."
  },
  {
    id: "u_p_303w116_3",
    propertyId: "p_303w116",
    label: "3",
    tenantName: "",
    tenantPhone: "",
    tenantEmail: "",
    leaseStart: "",
    leaseEnd: "",
    rent: 6495,
    stabilized: false,
    status: "vacant",
    notes: "$6,495/mo in the Jul 2026 blast \u2014 confirm status."
  },
  {
    id: "u_p_303w116_retail",
    propertyId: "p_303w116",
    label: "Retail",
    tenantName: "",
    tenantPhone: "",
    tenantEmail: "",
    leaseStart: "",
    leaseEnd: "",
    rent: 0,
    stabilized: false,
    status: "vacant",
    notes: "\u00b11,500 SF ground floor. Asking on request."
  },
  {
    id: "u_p_1875lex_4c",
    propertyId: "p_1875lex",
    label: "4C",
    tenantName: "",
    tenantPhone: "",
    tenantEmail: "",
    leaseStart: "",
    leaseEnd: "",
    rent: 3495,
    stabilized: false,
    status: "vacant",
    notes: "$3,495/mo, available now per the Aug 2026 blast."
  },
  {
    id: "u_p_1875lex_3d",
    propertyId: "p_1875lex",
    label: "3D",
    tenantName: "",
    tenantPhone: "",
    tenantEmail: "",
    leaseStart: "",
    leaseEnd: "",
    rent: 3695,
    stabilized: false,
    status: "vacant",
    notes: "$3,695/mo, available 28 Aug 2026."
  },
  {
    id: "u_p_1875lex_5c",
    propertyId: "p_1875lex",
    label: "5C",
    tenantName: "",
    tenantPhone: "",
    tenantEmail: "",
    leaseStart: "",
    leaseEnd: "",
    rent: 3595,
    stabilized: false,
    status: "vacant",
    notes: "$3,595/mo in the Jul 2026 blast \u2014 confirm status."
  },
  {
    id: "u_p_6aveb_6",
    propertyId: "p_6aveb",
    label: "6",
    tenantName: "",
    tenantPhone: "",
    tenantEmail: "",
    leaseStart: "",
    leaseEnd: "",
    rent: 5495,
    stabilized: false,
    status: "vacant",
    notes: "$5,495/mo, available now per the Aug 2026 blast."
  },
  {
    id: "u_p_6aveb_3",
    propertyId: "p_6aveb",
    label: "3",
    tenantName: "",
    tenantPhone: "",
    tenantEmail: "",
    leaseStart: "",
    leaseEnd: "",
    rent: 0,
    stabilized: false,
    status: "vacant",
    notes: "Listed as Inquire in the Jul 2026 blast \u2014 no rent published. Confirm status."
  }
]

export const PORTFOLIO_COMPLIANCE: ComplianceItem[] = [
  {
    id: "c_p_303w116_0",
    propertyId: "p_303w116",
    kind: "filing",
    title: "HPD Annual Property Registration",
    agency: "HPD",
    dueDate: "2026-09-01",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Due 1 September. An unregistered building cannot certify violations or sue for rent.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_303w116_1",
    propertyId: "p_303w116",
    kind: "filing",
    title: "HPD Bedbug Annual Report (LL69)",
    agency: "HPD",
    dueDate: "2026-12-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Prior-year infestation and eradication history, filed and distributed to tenants.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_303w116_2",
    propertyId: "p_303w116",
    kind: "filing",
    title: "Lead Paint Annual Notice (LL1)",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Deliver 1-16 Jan, tenant returns by 15 Feb, then inspect. Keep the returned forms.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_303w116_3",
    propertyId: "p_303w116",
    kind: "filing",
    title: "Window Guard Annual Notice",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Same cycle as the lead notice.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_303w116_4",
    propertyId: "p_303w116",
    kind: "filing",
    title: "LL55 Indoor Allergen Hazard Inspection",
    agency: "HPD",
    dueDate: "2027-01-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Annual inspection for mould and pests, plus one at every turnover.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_1875lex_0",
    propertyId: "p_1875lex",
    kind: "filing",
    title: "HPD Annual Property Registration",
    agency: "HPD",
    dueDate: "2026-09-01",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Due 1 September. An unregistered building cannot certify violations or sue for rent.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_1875lex_1",
    propertyId: "p_1875lex",
    kind: "filing",
    title: "HPD Bedbug Annual Report (LL69)",
    agency: "HPD",
    dueDate: "2026-12-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Prior-year infestation and eradication history, filed and distributed to tenants.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_1875lex_2",
    propertyId: "p_1875lex",
    kind: "filing",
    title: "Lead Paint Annual Notice (LL1)",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Deliver 1-16 Jan, tenant returns by 15 Feb, then inspect. Keep the returned forms.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_1875lex_3",
    propertyId: "p_1875lex",
    kind: "filing",
    title: "Window Guard Annual Notice",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Same cycle as the lead notice.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_1875lex_4",
    propertyId: "p_1875lex",
    kind: "filing",
    title: "LL55 Indoor Allergen Hazard Inspection",
    agency: "HPD",
    dueDate: "2027-01-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Annual inspection for mould and pests, plus one at every turnover.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_6aveb_0",
    propertyId: "p_6aveb",
    kind: "filing",
    title: "HPD Annual Property Registration",
    agency: "HPD",
    dueDate: "2026-09-01",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Due 1 September. An unregistered building cannot certify violations or sue for rent.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_6aveb_1",
    propertyId: "p_6aveb",
    kind: "filing",
    title: "HPD Bedbug Annual Report (LL69)",
    agency: "HPD",
    dueDate: "2026-12-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Prior-year infestation and eradication history, filed and distributed to tenants.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_6aveb_2",
    propertyId: "p_6aveb",
    kind: "filing",
    title: "Lead Paint Annual Notice (LL1)",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Deliver 1-16 Jan, tenant returns by 15 Feb, then inspect. Keep the returned forms.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_6aveb_3",
    propertyId: "p_6aveb",
    kind: "filing",
    title: "Window Guard Annual Notice",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Same cycle as the lead notice.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_6aveb_4",
    propertyId: "p_6aveb",
    kind: "filing",
    title: "LL55 Indoor Allergen Hazard Inspection",
    agency: "HPD",
    dueDate: "2027-01-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Annual inspection for mould and pests, plus one at every turnover.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_515w47_0",
    propertyId: "p_515w47",
    kind: "filing",
    title: "HPD Annual Property Registration",
    agency: "HPD",
    dueDate: "2026-09-01",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Due 1 September. An unregistered building cannot certify violations or sue for rent.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_515w47_1",
    propertyId: "p_515w47",
    kind: "filing",
    title: "HPD Bedbug Annual Report (LL69)",
    agency: "HPD",
    dueDate: "2026-12-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Prior-year infestation and eradication history, filed and distributed to tenants.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_515w47_2",
    propertyId: "p_515w47",
    kind: "filing",
    title: "Lead Paint Annual Notice (LL1)",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Deliver 1-16 Jan, tenant returns by 15 Feb, then inspect. Keep the returned forms.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_515w47_3",
    propertyId: "p_515w47",
    kind: "filing",
    title: "Window Guard Annual Notice",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Same cycle as the lead notice.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_515w47_4",
    propertyId: "p_515w47",
    kind: "filing",
    title: "LL55 Indoor Allergen Hazard Inspection",
    agency: "HPD",
    dueDate: "2027-01-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Annual inspection for mould and pests, plus one at every turnover.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_323e108_0",
    propertyId: "p_323e108",
    kind: "filing",
    title: "HPD Annual Property Registration",
    agency: "HPD",
    dueDate: "2026-09-01",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Due 1 September. An unregistered building cannot certify violations or sue for rent.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_323e108_1",
    propertyId: "p_323e108",
    kind: "filing",
    title: "HPD Bedbug Annual Report (LL69)",
    agency: "HPD",
    dueDate: "2026-12-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Prior-year infestation and eradication history, filed and distributed to tenants.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_323e108_2",
    propertyId: "p_323e108",
    kind: "filing",
    title: "Lead Paint Annual Notice (LL1)",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Deliver 1-16 Jan, tenant returns by 15 Feb, then inspect. Keep the returned forms.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_323e108_3",
    propertyId: "p_323e108",
    kind: "filing",
    title: "Window Guard Annual Notice",
    agency: "HPD",
    dueDate: "2027-02-15",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Same cycle as the lead notice.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  },
  {
    id: "c_p_323e108_4",
    propertyId: "p_323e108",
    kind: "filing",
    title: "LL55 Indoor Allergen Hazard Inspection",
    agency: "HPD",
    dueDate: "2027-01-31",
    recurrence: "annual",
    status: "scheduled",
    reference: "",
    notes: "Annual inspection for mould and pests, plus one at every turnover.\n\n\u26a0\ufe0f Seeded from the standard citywide date, not verified for this building. Confirm with the agency, and check whether the owner already files it.",
    lastCompleted: null,
    createdAt: "2026-08-31T16:11:56.013433"
  }
]

export const PORTFOLIO_TASKS: Task[] = [
  {
    id: "t_p_303w116_0",
    title: "Get HPD registration #, block & lot, and the super's name + cell \u2014 303 W 116th St",
    propertyId: "p_303w116",
    unitId: null,
    status: "open",
    priority: "high",
    category: "admin",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_303w116_1",
    title: "Pull open HPD and DOB/ECB violations \u2014 303 W 116th St",
    propertyId: "p_303w116",
    unitId: null,
    status: "open",
    priority: "high",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_303w116_2",
    title: "Look up LL152 gas piping cycle, and confirm FISP / elevator / boiler applicability \u2014 303 W 116th St",
    propertyId: "p_303w116",
    unitId: null,
    status: "open",
    priority: "normal",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-11",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_1875lex_0",
    title: "Get HPD registration #, block & lot, and the super's name + cell \u2014 1875 Lexington Ave",
    propertyId: "p_1875lex",
    unitId: null,
    status: "open",
    priority: "high",
    category: "admin",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_1875lex_1",
    title: "Pull open HPD and DOB/ECB violations \u2014 1875 Lexington Ave",
    propertyId: "p_1875lex",
    unitId: null,
    status: "open",
    priority: "high",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_1875lex_2",
    title: "Look up LL152 gas piping cycle, and confirm FISP / elevator / boiler applicability \u2014 1875 Lexington Ave",
    propertyId: "p_1875lex",
    unitId: null,
    status: "open",
    priority: "normal",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-11",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_6aveb_0",
    title: "Get HPD registration #, block & lot, and the super's name + cell \u2014 6 Avenue B",
    propertyId: "p_6aveb",
    unitId: null,
    status: "open",
    priority: "high",
    category: "admin",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_6aveb_1",
    title: "Pull open HPD and DOB/ECB violations \u2014 6 Avenue B",
    propertyId: "p_6aveb",
    unitId: null,
    status: "open",
    priority: "high",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_6aveb_2",
    title: "Look up LL152 gas piping cycle, and confirm FISP / elevator / boiler applicability \u2014 6 Avenue B",
    propertyId: "p_6aveb",
    unitId: null,
    status: "open",
    priority: "normal",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-11",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_515w47_0",
    title: "Get HPD registration #, block & lot, and the super's name + cell \u2014 515 W 47th St",
    propertyId: "p_515w47",
    unitId: null,
    status: "open",
    priority: "high",
    category: "admin",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_515w47_1",
    title: "Pull open HPD and DOB/ECB violations \u2014 515 W 47th St",
    propertyId: "p_515w47",
    unitId: null,
    status: "open",
    priority: "high",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_515w47_2",
    title: "Look up LL152 gas piping cycle, and confirm FISP / elevator / boiler applicability \u2014 515 W 47th St",
    propertyId: "p_515w47",
    unitId: null,
    status: "open",
    priority: "normal",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-11",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_323e108_0",
    title: "Get HPD registration #, block & lot, and the super's name + cell \u2014 323 E 108th St",
    propertyId: "p_323e108",
    unitId: null,
    status: "open",
    priority: "high",
    category: "admin",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_323e108_1",
    title: "Pull open HPD and DOB/ECB violations \u2014 323 E 108th St",
    propertyId: "p_323e108",
    unitId: null,
    status: "open",
    priority: "high",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-04",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  },
  {
    id: "t_p_323e108_2",
    title: "Look up LL152 gas piping cycle, and confirm FISP / elevator / boiler applicability \u2014 323 E 108th St",
    propertyId: "p_323e108",
    unitId: null,
    status: "open",
    priority: "normal",
    category: "compliance",
    assignee: "",
    dueDate: "2026-09-11",
    detail: "Onboarding a building you've just taken over. Everything else keys off these.",
    thread: [],
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433",
    completedAt: null
  }
]

export const PORTFOLIO_NOTES: Note[] = [
  {
    id: "n_start",
    body: "Buildings confirmed as ours so far: 303 W 116th St, 1875 Lexington Ave, 6 Avenue B, 515 W 47th St, 323 E 108th St. Ask the office for the full managed schedule \u2014 this is only the part I know.",
    propertyId: null,
    unitId: null,
    taskId: null,
    tags: [
      "onboarding"
    ],
    pinned: true,
    photoIds: [],
    createdAt: "2026-08-31T16:11:56.013433"
  }
]
